name: Build and Push Docker Image

# 修改这里：改为手动触发
on:
  workflow_dispatch: # 这行代码开启了手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          # 记得确保这里的用户名和仓库名正确
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tmdbbot:latest
